AmadoAccounting/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

urlpatterns = [
    path('uploadsalary', views.upload_salary,name='upload_salary'),
]

AmadoWH/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

from AmadoWH.mysite import site


from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('myadmin/', admin.site.urls),
    path('admin/', site.urls),
    # path('admin/', admin.site.urls),
    path('admin/AmadoAccounting/view/',include('AmadoAccounting.urls')),
    path('admin/AmadoFinance/view/',include('AmadoFinance.urls')),
    path('report/',include('AmadoWHApp.urls')),
    path('admin/ActualCost/',include('ActualCost.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AmadoAccounting/models.py
from django.db import models
from django_jalali.db import models as jmodels
import jdatetime
from django_jalali.db import models as jmodels
from django.contrib.auth.models import User
from AmadoFinance.models import BankAccount
from django.utils.safestring import mark_safe
import jdatetime
class Division(models.Model):
    title = models.CharField(max_length=128,verbose_name='عنوان')
    is_for_factory = models.BooleanField(verbose_name='بخش آماده سازی می باشد',default=False)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'بخش'
        verbose_name_plural = "بخش ها"
        permissions = (
            ("can_see_division", "می تواند مشاهده کند"),
        )


class Role(models.Model):
    title = models.CharField(max_length=128, verbose_name='عنوان')
    division = models.ForeignKey(Division,verbose_name='بخش مربوطه',on_delete=models.CASCADE)
    branch = models.ManyToManyField('AmadoWHApp.Branch',verbose_name='شعبه مربوطه')

    def __str__(self):
        return '%s شعبه %s'%(self.title,self.branch.last())

    class Meta:
        verbose_name = 'نقش'
        verbose_name_plural = "نقش ها"
        permissions = (
            ("can_see_role", "می تواند مشاهده کند"),
        )

class Person(models.Model):
    name = models.CharField(max_length=128,verbose_name='نام')
    nat_id = models.CharField(max_length=10,verbose_name='شماره ملی',null=True,blank=True)
    birth_day = jmodels.jDateField(verbose_name='تاریخ تولد',null=True,blank=True)
    image = models.FileField(upload_to='AmadoWH/static/Staff/Picture', null=True, blank=True, verbose_name="عکس پرسنلی")
    kart_melli = models.FileField(upload_to='AmadoWH/static/Staff/ID', null=True, blank=True, verbose_name="کارت ملی و شناسنامه")
    behdasht = models.FileField(upload_to='AmadoWH/static/Staff/Health', null=True, blank=True, verbose_name="کارت بهداشت")
    sooepishine = models.FileField(upload_to='AmadoWH/static/Staff/Sooepishine', null=True, blank=True, verbose_name="گواهی عدم سوء پیشینه")
    banks = models.ManyToManyField('AmadoFinance.BankAccount',verbose_name='حساب های فرد',related_name='pbankp',null=True,blank=True)
    
    # two_shift = models.BooleanField('حضور دو شیفت',default=True)
    childs = models.IntegerField(verbose_name='تعداد فرزندان',default=0)
    
    rem_vacations = models.FloatField(verbose_name='مرخصی مانده از سال %i'%(jdatetime.datetime.now().year-1),default=0)

    insurance_start_date = jmodels.jDateField(verbose_name='تاریخ شروع بیمه',null=True,blank=True)
    insurance_finish_date = jmodels.jDateField(verbose_name='تاریخ پایان بیمه',null=True,blank=True)

    def __str__(self):
        r = RoleHistory.objects.filter(person__id=self.id).order_by('start_date').last().role
        role = Role.objects.get(id=r.id)
        return '%s %s'%(self.name,r)

    class Meta:
        verbose_name = 'فرد'
        verbose_name_plural = "افراد"
        permissions = (
            ("can_see_person", "می تواند مشاهده کند"),
        )


class LawConstant(models.Model):
    date = jmodels.jDateField(verbose_name='تاریخ قانون', default=jdatetime.datetime.today().strftime('%Y-%m-%d'),unique=True)

    vezarat_kar_base = models.IntegerField(verbose_name='حقوق پایه وزارت کار', default=11112690)
    maskan_base = models.IntegerField(verbose_name='پایه حق مسکن', default=400000)  # 400000/31 * hoghoogh
    min_child = models.IntegerField(verbose_name='حداقل تعداد فرزند', default=1)  #0=0,1 = *3,>1 = *6
    bon_base = models.IntegerField(verbose_name='پایه حق بن', default=1100000)
    year_days = models.IntegerField(verbose_name='تعداد روزهای سال', default=365)
    week_base = models.IntegerField(verbose_name='حداقل ساعات کار ماهانه', default=220)  # 220
    extra_percentage = models.FloatField(verbose_name='درصد اضافه کاری', default=1.4)  # 1.4
    bime_percentage = models.FloatField(verbose_name='درصد بیمه', default=7)  # 7
    tax_bime_ratio = models.FloatField(verbose_name='کسر بیمه مالیات', default=0.28571429)  # 2/7
    tax_percentage = models.IntegerField(verbose_name='درصد مالیات', default=10)  # 10%
    kargar_bime_ratio1 = models.FloatField(verbose_name='درصد حق کارگر در بیمه', default=23)
    tax_min = models.IntegerField(verbose_name='حداقل پایه حقوق برای محاسبه مالیات',default=23000000)

    delivery_base = models.IntegerField(verbose_name='پایه حق پیک',default=10000)
    salad_base = models.IntegerField(verbose_name='پایه حق سالاد',default=10000)

    def __str__(self):
        return self.date.strftime('%Y-%m-%d')

    class Meta:
        verbose_name = 'ثابت حقوقی'
        verbose_name_plural = "ثابت های حقوقی"
        permissions = (
            ("can_see_lawconstant", "می تواند مشاهده کند"),
        )


class BaseAgreement(models.Model):
    # date = jmodels.jDateField(verbose_name='تاریخ توافق',default=jdatetime.datetime.today().strftime('%Y-%m-%d'))
    date = jmodels.jDateField(verbose_name='تاریخ توافق',default='1397-05-01')
    person = models.ForeignKey(Person,verbose_name='فرد',on_delete=models.CASCADE)

    base = models.IntegerField(verbose_name='مبلغ توافقی')
    two_shift = models.BooleanField('حضور دو شیفت', default=True)
    
    snapp_fee = models.IntegerField(verbose_name='حق اسنپ',default=0)


    def __str__(self):
        return '%s %s' % (self.person, self.date)

    class Meta:
        verbose_name = 'توافق حقوقی'
        verbose_name_plural = "توافقات حقوقی"
        permissions = (
            ("can_see_agreement", "می تواند مشاهده کند"),
        )

class RoleHistory(models.Model):
    start_date = jmodels.jDateField(verbose_name='تاریخ شروع')
    finish_date = jmodels.jDateField(verbose_name='تاریخ پایان',null=True,blank=True)

    person = models.ForeignKey(Person,verbose_name='فرد',on_delete=models.CASCADE)
    role = models.ForeignKey(Role,verbose_name='نقش',on_delete=models.CASCADE)

    # def __str__(self):
    #     return self.title

    class Meta:
        verbose_name = 'تاریخچه نقش'
        verbose_name_plural = "تاریخچه ها"
        permissions = (
            ("can_see_rolehistory", "می تواند مشاهده کند"),
        )


class SalaryDetail(models.Model):  # all rial
    person = models.ForeignKey(Person, verbose_name='فرد', on_delete=models.CASCADE)

    salary = models.ForeignKey('Salary', verbose_name='پرونده حقوق مربوطه', on_delete=models.CASCADE)

    days = models.IntegerField(verbose_name='تعداد روزهای کارکرد')
    fix = models.IntegerField(verbose_name='حقوق ثابت')
    base = models.IntegerField(verbose_name='حقوق پایه دوره')
    agreement = models.IntegerField(verbose_name='حقوق توافقی دوره')
    maskan = models.IntegerField(verbose_name='حق مسکن')
    childs = models.IntegerField(verbose_name='تعداد فرزند')  # if childs > 3 or ...
    childs_money = models.IntegerField(verbose_name='حق اولاد')
    bon = models.IntegerField(verbose_name='بن')
    sanavat = models.IntegerField(verbose_name='سنوات')
    hoghoogh_vezarat_kar_tot = models.IntegerField(verbose_name='جمع حقوق وزارت کار')
    positive_taraz = models.IntegerField(verbose_name='تراز مثبت')
    mazaya = models.IntegerField(verbose_name='مزایای شغلی',null=True,blank=True)
    extra_shift = models.FloatField(verbose_name='شیفت اضافه')
    extra_shift_fee = models.IntegerField(verbose_name='مزد شیفت اضافه')
    del_sal = models.IntegerField(verbose_name='پیک/سالاد')
    del_sal_fee = models.IntegerField(verbose_name='حق پیک/سالاد')
    
    vacation_rem = models.FloatField(verbose_name='مرخصی نرفته')
    vacation_rem_fee = models.IntegerField(verbose_name='حق طلب مرخصی')
    eydi = models.IntegerField(verbose_name='عیدی')
    
    off = models.FloatField(verbose_name='ایام تعطیل کاری')
    off_fee = models.IntegerField(verbose_name='مبلغ تعطیل کاری')
    extra_hours = models.IntegerField(verbose_name='ساعت اضافه کاری',null=True,blank=True)
    extra_hours_fee = models.IntegerField(verbose_name='مبلغ اضافه کاری')
    reward = models.IntegerField(verbose_name='پاداش',null=True,blank=True)
    snapp = models.IntegerField(verbose_name='حق اسنپ',null=True,blank=True)
    hoghoogh_mazaya_plus = models.IntegerField(verbose_name='جمع حقوق و مزایا')
    help = models.IntegerField(verbose_name='مساعده',null=True,blank=True)
    negative_taraz = models.IntegerField(verbose_name='تراز منفی')
    other_deduction = models.IntegerField(verbose_name='سایر کسورات',null=True,blank=True)
    fine = models.IntegerField(verbose_name='جریمه',null=True,blank=True)
    bime = models.IntegerField(verbose_name='بیمه',null=True,blank=True)
    maliat = models.IntegerField(verbose_name='مالیات',null=True,blank=True)
    kosoorat_sum = models.IntegerField(verbose_name='جمع کسورات')
    pardakhti = models.IntegerField(verbose_name='حقوق پرداختی')
    karfarma_bime = models.IntegerField(verbose_name='بیمه سهم کارفرما')

    account = models.ForeignKey('AmadoFinance.BankAccount',on_delete=models.CASCADE,verbose_name='حساب بانکی')

    description = models.TextField(max_length=512,verbose_name='توضیحات',null=True,blank=True)



    status = (
        ('registered', 'ثبت شده/در انتظار تایید'),
        ('confirmed', 'تایید شده/در انتظار امضای تسویه'),
        ('pending', 'در انتظار پرداخت'),
        ('paid', 'پرداخت شده'),
        ('error', 'نقص مدارک'),
    )

    payment_status = models.CharField(choices=status, max_length=16, verbose_name='وضعیت حقوقی',
                                      default='registered')

    add_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="ثبت کننده",
                                 related_name="salary_register_user", null=True, blank=True)
    add_date = jmodels.jDateTimeField(null=False, blank=False, verbose_name="تاریخ ثبت",
                                       default=jdatetime.datetime.now)
                                    #   default="1397-03-28 20:38:00")

    confirm_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="تایید کننده",
                                     related_name="salary_confirm_user", null=True, blank=True)

AmadoAccounting/templates/epayment_change_form.html
{% extends "admin/change_form.html" %}
{% load i18n admin_static %}

{% block extrahead %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

{{ block.super }}

    <script>
    $(document).ready(function () {

        if ($("#id_payment_type").val() !='help')
            $("div.field-payment_date").hide()

        $("#id_payment_type").change(function (event) {
            if ($(this).val()=='help'){
                $("div.field-payment_date").show()
            }
            else{
                $("div.field-payment_date").hide()
            }
        })

    })
    </script>



{% endblock %}

AmadoAccounting/templates/person_change_list.html
{% extends "admin/change_list.html" %}
{% load i18n admin_static %}

{% block extrahead %}

    {{ block.super }}

    <script type="text/javascript" src="/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js"></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js"></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/scripts/calendar.js"></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js"></script>
    <link href="/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css" type="text/css" media="all" rel="stylesheet" />
    <link href="/AmadoWHApp/static/admin/css/main.css" type="text/css" media="all" rel="stylesheet" />
    <link href="/AmadoWHApp/static/admin/css/vendor/select2/select2.css" type="text/css" media="screen" rel="stylesheet" />


    <script>

        $(document).ready(function(event){
            
            $('.actions select').on('change', function() {
              if (this.value == 'get_salary'){
                  $("thead tr").append('<th style="text-align:center" scope="col" class="column-__str__">'+
                                   '<div class="text"><span>محاسبه مرخصی</span></div>'+
                                   '<div class="clear"></div>'+
                                '</th>')

            $("thead tr").append('<th style="text-align:center" scope="col" class="column-__str__">'+
                                   '<div class="text"><span>مرخصی های مانده تا ماه قبل </span></div>'+
                                   '<div class="clear"></div>'+
                                '</th>')

            $("thead tr").append('<th style="text-align:center" scope="col" class="column-__str__">'+
                                   '<div class="text"><span>محاسبه عیدی</span></div>'+
                                   '<div class="clear"></div>'+
                                '</th>')
                                
            $("thead tr").append('<th style="text-align:center" scope="col" class="column-__str__">'+
                                   '<div class="text"><span>روز های کارکرد از اول امسال </span></div>'+
                                   '<div class="clear"></div>'+
                                '</th>')

            $(".results tbody tr").each(function (element) {
                id = $(this).children('.action-checkbox').children('input').val()
                $(this).append("<td><input type='checkbox' name='v"+id+"' value='"+id+"' ></td>")
                $(this).append("<td><input type='number'style='width: 50pt;' name='vnum"+id+"'  ></td>")
                $(this).append("<td><input type='checkbox' name='eydi"+id+"' value='"+id+"' ></td>")
                $(this).append("<td><input type='number'style='width: 50pt;' name='eydinum"+id+"'  ></td>")
            })


            

              }
            });

$("#changelist-form").prepend('<label for="id_from_date">از تاریخ: </label>\
        <input type="text" name="from_date" value="1398-01-01" class="vjDateField" size="10" required="" id="id_from_date">\
    &nbsp;&nbsp;\
        <label for="id_to_date">تا تاریخ: </label>\
        <input type="text" name="to_date" value="1398-01-31" class="vjDateField" size="10" required="" id="id_to_date">')
            

            $('.vjDateField').datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true,
                showOn: 'both',
                buttonImage: 'http://amadowh.ir/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/themes/base/images/icon-calendar.svg',
                buttonImageOnly: true,
            //     minDate: $('.vjDateField').val(),
            //     maxDate: '+30Y',
            });
            
            

            
        })


    </script>

{% endblock %}

AmadoAccounting/templates/salary_change_list.html
{% extends "admin/change_list.html" %}
{% load i18n admin_static %}


{% block object-tools %}
{{ block.super }}
    <form method="post" action="../view/uploadsalary" enctype="multipart/form-data">

        <label for="id_date">تاریخ: </label>
        <input type="text" name="date" value="{{ from_date }}" class="vjDateField" size="10" required="" id="id_date">

        &nbsp;&nbsp;

        <label for="id_branch">شعبه: </label>
        <select name="branch">
<!--            <option value=3>پونک</option>-->
            <option value=4>جنت آباد</option>
<!--            <option value=5>سعادت آباد</option>-->
<!--            <option value=6>گلستان</option>-->
<!--            <option value=7>هایپراستار</option>-->
            <option value=8>آماده سازی</option>
            <option value=9>دفتر مرکزی</option>
            <option value=11>تسویه شده</option>
            <option value=10>عیدی</option>
        </select>

        &nbsp;&nbsp;

        <label for="salary">فایل حقوق: </label>
        {% csrf_token %}
        <input name="salary" type="file" id="salary" accept=".xls,.xlsx">

        <input type="submit" value="بارگزاری"/>
    </form>
{% endblock %}

{% block extrahead %}

    {{ block.super }}

    <script type="text/javascript" src="/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js"></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js"></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/scripts/calendar.js"></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js"></script>
    <link href="/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css" type="text/css" media="all" rel="stylesheet" />
    <link href="/AmadoWHApp/static/admin/css/main.css" type="text/css" media="all" rel="stylesheet" />
    <link href="/AmadoWHApp/static/admin/css/vendor/select2/select2.css" type="text/css" media="screen" rel="stylesheet" />


    <script>

        $(document).ready(function(event){

            $('.vjDateField').datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true,
                showOn: 'both',
                buttonImage: 'http://amadowh.ir/admin/AmadoWHApp/static/admin/jquery.ui.datepicker.jalali/themes/base/images/icon-calendar.svg',
                buttonImageOnly: true,
            //     minDate: $('.vjDateField').val(),
            //     maxDate: '+30Y',
            });
            
            

            
        })


    </script>

{% endblock %}

AmadoAccounting/templates/salary_det_change_list.html
{% extends "admin/change_list.html" %}
{% load i18n admin_static %}

{% block extrahead %}

    {{ block.super }}

    <script type="text/javascript" src='https://ajax.googleapis.com/ajax/libs/jquery/2.2.3/jquery.min.js'></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/js/admin/jalalijscalendar/jalali.js"></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/js/admin/jalalijscalendar/calendar.js"></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/js/admin/jalalijscalendar/calendar-setup.js"></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/js/admin/jalalijscalendar/calendar-fa.js"></script>
    <script type="text/javascript" src="/AmadoWHApp/static/admin/js/admin/jDateTimeShortcuts.js"></script>
    <link href="/AmadoWHApp/static/admin/css/calendar-green.css" type="text/css" media="all" rel="stylesheet" />
    <link href="/AmadoWHApp/static/admin/css/vendor/select2/select2.css" type="text/css" media="screen" rel="stylesheet" />



    <script>

        $(document).ready(function(event){

            $("#result_list").append(
                "<tr>" +
                    "<td></td>"+
                    "<td></td>"+
                    "<td></td>"+
                    "<td></td>"+
                    "<th style='text-align:center'>جمع</th>"+
                    "<th style='text-align:center;'>{{ cl.tomato_count }}</th>" +
                    "<th style='text-align:center;background-color: #8effbf;'>{{ cl.tomato_count1 }}</th>" +
                    "<td></td>"+
                    "<td></td>"+
                "</tr>")



        })


    </script>

    <style>
        .field-remainder,.column-remainder{
            background-color: #8effbf;
        }
    </style>

{% endblock %}

AmadoAccounting/templates/work_change_form.html
{% extends "admin/change_form.html" %}
{% load i18n admin_static %}

{% block extrahead %}
{{ block.super }}

    <script>
    $(document).ready(function () {

        if (window.location.href.includes('/add/')){



            {% for p in persons %}
                $("#id_workdetail_set-{{ forloop.counter0 }}-work_status").prepend('<option value="" selected="">---------</option>')
                $("#id_workdetail_set-{{ forloop.counter0 }}-person").append('<option value="{{ p.id }}">{{ p }}</option>')


                $("#select2-id_workdetail_set-{{ forloop.counter0 }}-person").attr('title','{{ p }}')
                $("#select2-id_workdetail_set-{{ forloop.counter0 }}-person").html('{{ p }}')
            {% endfor %}
        }

    })
    </script>


{% endblock %}